version: '3'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-api
    stdin_open: true
    tty: true #コンテナの永続化
    depends_on:
      - mysql
      - redis
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    ports:
      - ${SERVER_PORT}:${CONTAINER_SERVER_PORT}
    networks:
      - 02-recipe-api-network

  mysql:
    container_name: 02-recipe-mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    expose:
      - ${DB_PORT}
    volumes:
      - ./mysql/migrations:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/sql
      - ./mysql/config/my.conf:/etc/mysql/conf.d/my.cnf
    # env_file:
    #   - ./app/app.env
    environment:
      # MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      # MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - 02-recipe-api-network

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    networks:
      - 02-recipe-api-network
  
  redis:
    image: redis:latest
    container_name: 02-recipe-redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - 02-recipe-api-network

networks:
  02-recipe-api-network:
    name: 02-recipe-api-network
